name: UnknownPlayers
author: MrEinStain
version: 2.0
main: net.unknownmc.players.UnknownPlayers
commands:
  player:
    description: Get a player's playtime.
    aliases: [playerinfo, plinfo, playtime, rankup]
    permissions: unknownmc.playtime
  demote:
    description: Demote a staff member.
    permissions: unknownmc.demote
permissions:
  unknownmc.playtime:
    default: true
  unknownmc.playtime.other:
    default: op
  unknownmc.player:
    default: false
  unknownmc.demote:
    default: op
